export const DEFAULT_DATA_CHUNKS = [
  "My name is Koushik and I am a software engineer.",
  "I work at a tech company where I build complex web applications and data pipelines.",
  "I am from India and currently live in a bustling city.",
  "I am very passionate about artificial intelligence, deep learning, and building tools.",
  "In my free time, I love to experiment with modern web frameworks and read about new machine learning research.",
  "Koushik has a strong background in developing frontend interfaces that simplify complex systems.",
  "As an experienced developer, Koushik loves creating visual tools for education and learning.",
  "When he's not coding, Koushik enjoys mentoring junior engineers and writing technical blogs.",
  "I am Dr. Elena Rossi, a senior researcher specializing in natural language processing.",
  "I work for the AI Research Institute based in London.",
  "My main project is designing efficient transformer models that require less memory for inference.",
  "I am passionate about making AI accessible and open source.",
  "My team builds systems that decode language patterns using advanced attention matrix calculations.",
  "The TransformerViz system is an interactive educational tool designed to visualize neural networks.",
  "It was created by a passionate developer to help users understand complex concepts.",
  "The system uses a fast in-browser vector database to perform contextual retrieval.",
  "Embeddings are high-dimensional vectors that represent the semantic meaning of tokens.",
  "The attention mechanism allows the model to weigh the importance of different words in a sentence.",
  "Query, Key, and Value matrices are the core of self-attention in a transformer model.",
  "Softmax converts raw logits into a probability distribution that sums to 1.0.",
  "Temperature scaling controls the randomness of predictions by dividing the logits before softmax.",
  "Top-K filtering restricts the model to only sample from the K most likely next tokens.",
  "Top-P (nucleus) filtering restricts sampling to the smallest set of tokens whose cumulative probability exceeds P.",
  "A Feed-Forward Network (FFN) applies non-linear transformations to individual tokens independently.",
  "Layer Normalization stabilizes training by normalizing the activations across the feature dimension.",
  "Positional encoding injects information about the order of tokens into the embeddings.",
  "Self-attention allows the model to look at the entire context of the sequence simultaneously.",
  "Multi-head attention runs several attention mechanisms in parallel to capture different types of relationships.",
  "The decoder block in GPT-style models uses masked self-attention to prevent looking into the future.",
  "Tokenization is the process of breaking raw text into smaller pieces called tokens.",
  "Logits are the raw, unnormalized scores output by the final linear layer of the neural network.",
  "A vector database stores embeddings and allows for fast similarity searches using metrics like cosine similarity.",
  "Retrieval-Augmented Generation (RAG) improves model responses by fetching relevant context from a database.",
  "Cosine similarity measures the angle between two vectors, completely ignoring their magnitude.",
  "Generative Pre-trained Transformers (GPT) are autoregressive language models that predict the next token.",
  "Large Language Models (LLMs) are trained on massive text corpora to learn the statistical patterns of language.",
  "Prompt engineering is the art of crafting inputs to guide the model towards a desired output.",
  "Context window refers to the maximum number of tokens the model can process in a single pass.",
  "Fine-tuning adapts a pre-trained model to a specific task using a smaller, specialized dataset.",
  "In-context learning allows the model to perform tasks simply by providing examples in the prompt.",
  "Zero-shot prompting asks the model to perform a task without providing any explicit examples.",
  "Few-shot prompting provides a few examples in the prompt to demonstrate the desired behavior.",
  "Hallucination occurs when the model generates plausible-sounding but factually incorrect information.",
  "Stochastic gradient descent is the primary optimization algorithm used to train neural networks.",
  "Backpropagation computes the gradients of the loss function with respect to the model's weights.",
  "The loss function measures the discrepancy between the model's predictions and the true labels.",
  "Activation functions like GELU and ReLU introduce non-linearity into the neural network.",
  "GELU (Gaussian Error Linear Unit) is commonly used in modern transformers like BERT and GPT.",
  "Dropout is a regularization technique that randomly sets a fraction of activations to zero during training.",
  "Overfitting happens when the model memorizes the training data but fails to generalize to unseen data.",
  "Underfitting occurs when the model is too simple to capture the underlying patterns in the data.",
  "Hyperparameters are settings configured before training, such as learning rate, batch size, and network depth.",
  "The learning rate determines the step size taken during gradient descent optimization."
];
